# Generated by Django 2.2.10 on 2020-07-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionitem',
            old_name='question_selected',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='name',
            field=models.CharField(choices=[('answer_text', 'Ответ текстом'), ('answer_one_selected', 'Ответ с выбором одного варианта'), ('answer_some_selected', 'Ответ с выбором нескольких вариантов')], max_length=256, verbose_name='Ответ на вопрос'),
        ),
    ]
