# Generated by Django 2.2.10 on 2020-08-01 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200731_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.Quiz', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Ответ на вопрос'),
        ),
    ]
