# Generated by Django 2.2.10 on 2020-08-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200801_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Question', verbose_name='Ответ с выбором'),
        ),
    ]
