# Generated by Django 2.2.10 on 2020-08-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200801_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_selected',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.QuestionItem', verbose_name='Ответы/Ответ на вопрос выбранные из списка ответов'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Вариант ответа'),
        ),
        migrations.DeleteModel(
            name='AnswerItem',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.User', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
