# Generated by Django 2.2.10 on 2020-08-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200802_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_selected',
            field=models.ManyToManyField(blank=True, to='quiz.QuestionItem', verbose_name='Ответы/Ответ на вопрос выбранные из списка ответов'),
        ),
    ]
